- plugin.video.uwc/resources/lib/sites/animeidhentai.py
- plugin.video.uwc/resources/lib/sites/beeg.py
> Update animeidhentai & beeg

- plugin.video.uwc/resources/lib/sites/beeg.py
- plugin.video.uwc/resources/lib/sites/herexxx.py
herexxx - fixed nextpage for search
beeg -  option 'Don't ask for videohost' from settings works for Beeg
> beeg & herexxx

- plugin.video.uwc/default.py
- plugin.video.uwc/resources/lib/sites/daftsex.py
- plugin.video.uwc/resources/lib/sites/hotpornfile.py
- plugin.video.uwc/resources/lib/sites/streamate.py
added hotpornfile.org
daftsex: updated server list + added timeout to searches
streamate: search fixed
> hotpornfile, daftsex, streamate

- plugin.video.uwc/resources/lib/sites/cam4.py
- plugin.video.uwc/resources/lib/sites/chaturbate.py
I added some info about the rooms in Chaturbate and Cam4
If you think it can be useful for all the users you can merge this update to the repository.
> Added info about room in Chaturbate and Cam4

- plugin.video.uwc/default.py
- plugin.video.uwc/resources/lib/sites/cumlouder.py
- plugin.video.uwc/resources/lib/sites/eroticage.py
- plugin.video.uwc/resources/lib/sites/spankbang.py
- plugin.video.uwc/resources/lib/sites/xvideospanish.py
- plugin.video.uwc/resources/lib/utils.py
added: cumlouder
fixed: eroticage, spankbang, xvideopanish
> cumlouder, eroticage, spankbang, xvideospanish

- plugin.video.uwc/resources/lib/sites/xhamster.py
Also fixes issues:
- After choosing categories gay or shemale, all listings would be of this category due to cookies
- Incorrect formatting of video names with special characters
On a side node, utils.cleantext should probably be changed to use HTMLParser.unescape. I didn't change it because I don't know if it would break other sites.
> xhamster: apply filters to all listings

- plugin.video.uwc/resources/lib/sites/hdporn.py
- plugin.video.uwc/resources/lib/sites/porndoe.py
Fixed directory, search & categories. Thanks @jdoedev123
> Porndoe & Woxtube fix.

- plugin.video.uwc/resources/lib/sites/freeomovie.py
Freeomovie wasn' t loading before.
> Fixed freeomovie

- plugin.video.uwc/resources/lib/sites/animeidhentai.py
Uncensored directory wasn't loading. Fixed url.
> Uncensored directory fix.

- plugin.video.uwc/default.py
- plugin.video.uwc/resources/lib/sites/paradisehill.py
> Paradisehill video play fix

- plugin.video.uwc/resources/lib/sites/beeg.py
Edited code to allow Beeg to load.  I'm still trying to learn Python & don't want to bombard a site with requests. If I'm doing something wrong can 12asdfg12 or  JDoeDev123 double check my pull requests, I would greatly appreciate it.
Thanks guys.
> Beeg wasn't loading before.

- plugin.video.uwc/resources/lib/sites/hdporn.py
Fixed directory loading & video playback.
Added Top-Rated directory.
> Fixed Porn00

- plugin.video.uwc/resources/lib/sites/paradisehill.py
> Paradisehill playback fix.

- plugin.video.uwc/resources/lib/sites/javhoho.py
- plugin.video.uwc/resources/lib/sites/vipporns.py
Fixed thumbnail not loading error.
> Thumbnail not loading fix.

- plugin.video.uwc/resources/lib/sites/ipornovideos.py
- plugin.video.uwc/resources/lib/sites/spankbang.py
Temporary fix for ipornvideos. I believe the code has to be cleaned up by a dev since jetload is no longer being used. Thanks.
Spankbang directory list fix.
> Iporn & Spankbag fix..

- plugin.video.uwc/resources/lib/utils.py
Instead of just sorting the keywords this adds another layer that lets you choose by alphabetical letter upfront. Usefull if you have quite a few keywords.
> Alphabetical Search

- plugin.video.cumination/resources/lib/sites/anybunny.py
- plugin.video.cumination/resources/lib/sites/daftsex.py
This caused the search function to not work & getting updated lists.
> Update Anybunny domain change.

- plugin.video.cumination/resources/lib/sites/netflixporno.py
Fix latest list for Netflixporno.
> Fix latest list for Netflixporno.

- plugin.video.cumination/resources/lib/sites/pornhub.py
> Pornhub List fix.

- plugin.video.cumination/resources/lib/utils.py
> correct auto quality selection for sources of hqporner with 60fps

- plugin.video.cumination/resources/lib/sites/paradisehill.py
Added Studio & Actor directories for Paradisehill. As @ErosVece stated that it would work well with the "look up info" context, I'm going to try implement in the future. I did try it out for a quick sec & it didn't work out.  I'm still learning Python. I'm still crawling with it, not walking. Thank you for the advices you guys are providing. I'm trying for a 47 year old.... We're never to old to learn....
> Added Studio & Actor directories for Paradisehill.

- plugin.video.cumination/resources/lib/sites/hentaihavenco.py
> Hentaihaven Video playback fix

- plugin.video.cumination/resources/lib/sites/sextb.py
List wasn't completely loading.
> Fix for partial directory list.

- plugin.video.cumination/resources/lib/sites/netfapx.py
> Netfapx playback fix..

- plugin.video.cumination/changelog.txt
- plugin.video.cumination/resources/lib/sites/porndig.py
The JSON-Dictionary of the video page changed. The "URL" key was renamed to "SRC".
> Fix playback for Porndig site
